mvc/Models/room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace mvc.Models
{
    public class User
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email_address { get; set; }
        public string user_name { get; set; }
        public string phone_number { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zip_code { get; set; }
    }
    public class Room
    {
        public int id { get; set; }
        [Display(Name = "Guests")]
        public int occupants { get; set; }
    }
    public class Reservation
    {
        public int id { get; set; }
        [Display(Name="Check In")]
        [DataType(DataType.Date)]
        public DateTime check_in_date { get; set; }
        [Display(Name = "Check Out")]
        [DataType(DataType.Date)]
        public DateTime check_out_date { get; set; }
        [Display(Name = "# Rooms")]
        public int room_count { get; set; }
        public DateTime reserve_date { get; set; }
        public DateTime cancel_date { get; set; }
        [Display(Name = "Notes")]
        public string notes { get; set; }

        [Display(Name = "Location")]
        public string geonameid { get; set; }
        public IEnumerable<Room> Rooms { get; set; }

    }
}

mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Tech specs and docs generated during challenge";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Full Stack .NET Developer";
            return View();
        }

        public ActionResult Admin()
        {
            ViewBag.Message = "Data must be administrated as well as coded";
            return View();
        }

        public ActionResult Reservation()
        {
            ViewBag.Message = "Reserve a room or rooms now";
            return View();
        }
    }
}

mvc/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mvc.DAL;
using mvc.Models;

namespace mvc.Controllers
{
    public class ReservationController : Controller
    {
        private ReservationContext db = new ReservationContext();

        // GET: Reservation
        public ActionResult Index()
        {
            return View(db.Reservations.ToList());
        }

        // GET: Reservation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reservation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,check_in_date,check_out_date,room_count,reserve_date,cancel_date,notes,user_id")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reservation);
        }

        // GET: Reservation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,check_in_date,check_out_date,room_count,reserve_date,cancel_date,notes,user_id")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reservation);
        }

        // GET: Reservation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "Code Challenge Documentation";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

mvc/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Code Challenge Administration";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Julie McFadden";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    10017 Bentley Way<br />
    Tampa, FL 33626<br />
    <abbr title="Phone">P:</abbr>
    501.772.7470
</address>

<address>
    <strong>Email:</strong><span style="margin-left: 20px;"><a href="mailto:she@juliemcfadden.com">she@juliemcfadden.com</a></span><br />
    <strong>Web:</strong><span style="margin-left: 27px;"><a href="http://www.juliemcfadden.com">www.juliemcfadden.com</a></span>
</address>

mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Landing Page";
}

<div class="jumbotron">
    <h1>Julie McFadden</h1>
    <p class="lead">Reservations.com Code Challenge</p>
    <p><a href="http://www.juliemcfadden.com" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Documentation</h2>
        <p>Database Schema Diagram, SQL Scripts, etc.</p>
        <p><a class="btn btn-default" href="/Home/About">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Administration</h2>
        <p>The internal user view of the data, including some basic reports</p>
        <p><a class="btn btn-default" href="/Home/Admin">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Reservations</h2>
        <p>The external user view of the application</p>
        <p><a class="btn btn-default" href="/Reservation/Index">Learn more &raquo;</a></p>
    </div>
</div>

mvc/Views/Home/Reservation.cshtml
@{
    ViewBag.Title = "The meat of the matter...";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

mvc/Views/Reservation/Create.cshtml
@model mvc.Models.Reservation

@{
    ViewBag.Title = "Reserve Room";
}

<h2>Reserve your Room</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reservation Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.geonameid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.geonameid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.geonameid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.check_in_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.check_in_date, new { htmlAttributes = new { @class = "form-control check_in" } })
                @Html.ValidationMessageFor(model => model.check_in_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.check_out_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.check_out_date, new { htmlAttributes = new { @class = "form-control check_out" } })
                @Html.ValidationMessageFor(model => model.check_out_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.room_count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.room_count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.room_count, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            var minDate = moment(new Date()).add(1, 'd').format('MM/DD/YYYY');
            console.log(minDate);


        });
    </script>
}

mvc/Views/Reservation/Delete.cshtml
@model mvc.Models.Reservation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.check_in_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_in_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.check_out_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_out_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.room_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room_count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reserve_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reserve_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cancel_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cancel_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mvc/Views/Reservation/Details.cshtml
@model mvc.Models.Reservation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.check_in_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_in_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.check_out_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.check_out_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.room_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.room_count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reserve_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reserve_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cancel_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cancel_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

mvc/Views/Reservation/Edit.cshtml
@model mvc.Models.Reservation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.check_in_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.check_in_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.check_in_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.check_out_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.check_out_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.check_out_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.room_count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.room_count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.room_count, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvc/Views/Reservation/Index.cshtml
@model IEnumerable<mvc.Models.Reservation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.geonameid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.check_in_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.check_out_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.room_count)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.geonameid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.check_in_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.check_out_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.room_count)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Code Challenge", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Docs", "About", "Home")</li>
                    <li>@Html.ActionLink("Admin", "Admin", "Home")</li>
                    <li>@Html.ActionLink("Rooms", "Reservation", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Julie McFadden</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>